fix getActionBar NoSuchMethodError
getActionBar is a method of api 11, so change to call getSupportActionBar instead
Also make the class extends SherlockFragmentActivity